module.exports = {
    UNEXPECTED_EXCEPTION: -1,
    // Error flags set in the powers of 2
    INVALID_CLIENT_INFO: 1,
    INVALID_REQUEST: 2,
    ACTION_INVALID: 4,
    ORDER_ID_INVALID: 8,
    ORDER_COMPLETED: 16,
    ORDER_MODIFY_PENDING: 32,

    INITIALIZE_ORDER_MISSING_GROUP: 64,
    INITIALIZE_ORDER_GROUP_MISSING_ITEM: 128,
    INITIALIZE_DUPLICATE_ORDER_GROUP: 256,
    INITIALIZE_INVALID_PRODUCT_ID: 512,
    INITIALIZE_INVALID_CLIENT_MEMBER_ID: 1024,
    INITIALIZE_INVALID_CLIENT_GROUP_REFERENCE_ID: 2048,
    INITIALIZE_INVALID_LOCATION_NUMBER: 4096,
    INITIALIZE_INVALID_PICKUPINFO: 8192,
    INITIALIZE_HAZMAT_RESTRICTED_ADDRESS: 16384,
    INITIALIZE_INVALID_SHIPPING_ADDRESS_TYPE: 32768,
    INITIALIZE_ORDER_MISSING_BILLING_ADDRESS: 65536,
    EXCESS_PROMOITEMPRICETEXT_CHARACTER_LENGTH: 131072,
    INITIALIZE_INVALID_REQUESTED_ARRIVAL_DATE: 262144,
    INITIALIZE_INVALID_LOCATION_TYPE_CODE: 524288,
    INITIALIZE_INVALID_ADDRESS_TYPE: 1048576,
    INITIALIZE_ORDER_MISSING_GIFT_MESSAGE_INFO: 2097152,
    INITIALIZE_ORDER_MISSING_GIFT_MESSAGE_INFO_SENDER_NAME: 4194304,
    INITIALIZE_ORDER_INVALID_LOCATION_INFORMATION: 8388608,
    INITIALIZE_ORDER_INVALID_PROMISED_DATE: 16777216,
    INITIALIZE_ORDER_DUPLICATE_GROUP_ID: 33554432,
    INITIALIZE_ORDER_DUPLICATE_LINEITEM_ID: 67108864,
    ORDER_IN_PROGESS_CANNOT_MODIFY: 64,
    MODIFY_ORDER_INVALID_CLIENT_GROUP_ID: 128,
    MODIFY_ORDER_INVALID_CLIENT_LINEITEM_ID: 256,
    MODIFY_ORDER_DUPLICATE_GROUP_ID: 512,
    MODIFY_ORDER_DUPLICATE_LINEITEM_ID: 1024,


    UNEXPECTED_EXCEPTION_MESSAGE: "An unexpected error has occurred.",
    INVALID_CLIENT_INFO_MESSAGE: "Invalid client id or site id.",
    INVALID_REQUEST_MESSAGE: "Request object is null.",
    ACTION_INVALID_MESSAGE: "Invalid Action specified for order modification.",
    ORDER_IN_PROGESS_CANNOT_MODIFY_MESSAGE: "Order is in progress and cannot be modified.",
    ORDER_ID_CLIENT_ID_INVALID_MESSAGE: "Invalid OrderId or ClientId.",
    ORDER_ID_INVALID_MESSAGE: "Invalid OrderId or ClientId.",
    ORDER_COMPLETED_MESSAGE: "Order is in completed status.",
    ORDER_MODIFY_PENDING_MESSAGE: "Order is in cancel pending status.",

    INITIALIZE_ORDER_MISSING_GROUP_MESSAGE: "The order does not have any groups.",
    INITIALIZE_ORDER_GROUP_MISSING_ITEM_MESSAGE: "One or more groups do not have any line items.",
    INITIALIZE_ORDER_MISSING_BILLING_ADDRESS_MESSAGE: "One or more groups do not have billing address.",
    INITIALIZE_DUPLICATE_ORDER_GROUP_MESSAGE: "Cannot inject duplicate client order id and client group id.",
    INITIALIZE_INVALID_PRODUCT_ID_MESSAGE: "Invalid product id: %s.",
    INITIALIZE_INVALID_CLIENT_MEMBER_ID_MESSAGE: "Could not find member information for the ClientMemberId: %s.",
    INITIALIZE_INVALID_CLIENT_GROUP_REFERENCE_ID_MESSAGE: "Client group reference id must contain 8 digits when the location type code is 2.",
    INITIALIZE_INVALID_LOCATION_NUMBER_MESSAGE: "Location number must contain 5 digits when the location type code is 2.",
    INITIALIZE_INVALID_PICKUPINFO_MESSAGE: "Invalid or missing pickup information for the address type PickupLocation.",
    INITIALIZE_HAZMAT_RESTRICTED_ADDRESS_MESSAGE: "Order contains hazmat product %s that cannot be shipped to %s.",
    INITIALIZE_INVALID_SHIPPING_ADDRESS_TYPE_MESSAGE: "Shipping address type must be pickup location when the location type code is non-zero.",

    ORDER_INJECTION_FAILURE_MESSAGE: "Order Injection failed.",
    ORDER_RETRIEVAL_FAILURE_MESSAGE: "Order Retrieval failed.",
    ORDER_MODIFY_FAILURE_MESSAGE: "Order modification failed.",
    ORDER_CLOSE_FAILURE_MESSAGE: "Order close failed.",

    EXCESS_PROMOITEMPRICETEXT_CHARACTER_LENGTH_MESSAGE: "PromoItemPriceText field cannot have more than 8 characters for group id %s and lineitem id %s.",
    INITIALIZE_INVALID_LOCATION_TYPE_CODE_MESSAGE : "Invalid Location Type code for the given siteId: %s.",
    INITIALIZE_INVALID_ADDRESS_TYPE_MESSAGE : "Invalid Address Type for the given siteId: %s.",
    INITIALIZE_INVALID_REQUESTED_ARRIVAL_DATE_MESSAGE: "Requested Arrival Date must be of the format yyyy-mm-dd when IsAutoReorder is true.",
    INITIALIZE_ORDER_DUPLICATE_GROUP_ID_MESSAGE: "Duplicate client group id %s found in the client order id %s.",
    INITIALIZE_ORDER_DUPLICATE_LINEITEM_ID_MESSAGE: "Duplicate client lineitem id %s found in the client group id %s and client order id %s.",
    INITIALIZE_ORDER_MISSING_GIFT_MESSAGE_INFO_MESSAGE: "Gift message info is required for client group id %s.",
    INITIALIZE_ORDER_MISSING_GIFT_MESSAGE_INFO_SENDER_NAME_MESSAGE: "The gift sender name is required in client group id %s.",
    INITIALIZE_ORDER_INVALID_LOCATION_INFORMATION_MESSAGE: "Invalid location id, location type combination for group id %s, lineitem id %s.",
    INITIALIZE_ORDER_INVALID_PROMISED_DATE_MESSAGE: "Promised Date for group id %s, lineitem id %s cannot be older than the order placed date.",
    MODIFY_ORDER_INVALID_CLIENT_GROUP_ID_MESSAGE: "Invalid client group id %s for the oms order id %s.",
    MODIFY_ORDER_INVALID_CLIENT_LINEITEM_ID_MESSAGE: "Invalid client lineitem id %s for group id %s and oms order id %s.",
    MODIFY_ORDER_DUPLICATE_GROUP_ID_MESSAGE: "Duplicate client group id %s found in the order modify request for the oms order id %s.",
    MODIFY_ORDER_DUPLICATE_LINEITEM_ID_MESSAGE: "Duplicate client lineitem id %s found in the order modify request for the client group id %s and oms order id %s.",

    ERROR_MESSAGE_SEPARATOR: " ",

    OMS: "OMS"
}